#!/usr/bin/env bash

set -efuxo pipefail

cargo build
cargo test
cargo doc

# -a:           Disable cache (it doesn't work well).
# -W:           Treat warnings as errors, as they're quite serious.
# --keep-going: Keep emitting warnings after the first one.
sphinx-build -a -W --keep-going manual target/manual
